### ISSUE TITLE
Put scene in a div

### ISSUE THREAD

**Issue by tim-9red7** [jhwohlgemuth/voxelcss#49]
**Expected behavior**
I'm trying to attach the scene to a div so it displays down the page a bit.
`scene.attach(document.getElementById('theDiv');`

**Actual behavior**
It attaches correctly in the DOM. However, the scene displays at the top of the page. 

Thoughts?

**Comment by edutim** [comment]
It isn't styled at all. It is a ways down the body of the HTML page (there is content above 'theDiv'). The voxelcss scene appears at the top of the body.

**Comment by jhwohlgemuth** [comment]
I am going to look into this more, but in the meantime you might try overriding voxelcss styles. 

Something like:

```css
.voxelcss-scene {
    position: relative;
}
```

I tried this using [demo.html](https://github.com/jhwohlgemuth/voxelcss/blob/master/test/demo/index.html) and it seemed to be a viable solution (at least for simple scenarios)

**Comment by edutim** [comment]
Thanks for that. That DOES fix the issue of placing it lower on the screen. Yay for that! However, it removes the ability of the camera to pan around the object! Erg. Thanks for taking a look.

**Comment by jhwohlgemuth** [comment]
Would you mind pasting your HTML and CSS? With that info, I will take a more directed look at this issue, maybe find a solution worth integrating back into the library.
